### ISSUE TITLE
CONTRIBUTING guidelines?

### ISSUE THREAD

**Issue by joshmorel** [SoftwareEngineeringDaily/sedaily-front-end#20]
For someone wanting to contribute - I think a CONTRIBUTING file that explains the repo's workflow process and the different branches would be helpful.

Specifically, it seems `mvp` is the active branch but what is the role of `master` then. And which is being deployed to  https://sedaily.herokuapp.com/#/ ? It's not the same as where `mvp` is right now but it's hard to tell if it's `master` because that's not working locally (for me at least, `mvp` is, however).

Also are there expectations around tests or any other conventions not otherwise obvious?

I'm willing to write it up based on discussion here from main contributors.

**Comment by jasonify** [comment]
Ahh, yeah. 

We should totally have such a file and we should consolidate our branches. 

Since it was mostly going to be @crablar  and I working on the repo and we wanted to quickly merge each other's work we created a temporary branch called MVP (to reach feature parity with ios).

The plan was to finish off by the end of the week and merge things back into master. It looks like we might be doing that on Monday / early next week.

**Comment by TheHollidayInn** [comment]
Sorry about the confusion! Master is currently default, so that should be the branch to focus on. We haven't set up CI or anything on this repo, so that may cause it to not be working. We will get that fixed!

We will get a Git Flow added to all our projects soon: https://github.com/SoftwareEngineeringDaily/SEDaily-Android/issues/10

**Comment by andrewmarklloyd** [comment]
Where are we at with this?

**Comment by crablar** [comment]
I haven't written any more about the contribution process since it is still a WIP. We have a manual process of pushing to staging.

We should add more to the Open Source Guide about finding the right people to contact on Slack.
