### ISSUE TITLE
Clean Up Feed Element Design

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#211]
Clean up the feed design to make the feed elements more like Facebook feed. Make everything smaller, more narrow. Leave lots of space in the margins for future design expansion.

Remove "Votes" from feed elements

Remove the word "Feed" at the top

**Comment by dasimandl** [comment]
@crablar @andrewmarklloyd  I am going to take a shot at this issue.

**Comment by dasimandl** [comment]
@crablar @andrewmarklloyd  Because the ForumThreadSummary and the FeedItem are basically doing the same thing, I was wondering if it makes more sense to do the conditional logic check for thread vs feed items within the component level, not at the FeedItemWrapper level.  Seems like this will make the code more DRY, make future maintenance / design changes to feed much easier,  and clear up confusing naming convention (ForumThreadSummary inside of FeedItemWrapper).

Please let me know if you approve of this approach, and I will start development.

**Comment by andrewmarklloyd** [comment]
@dasimandl without digging into the code too much that sounds reasonable. Let's just make sure that any changes to the feed do not affect the forum. We recently added the Cypress end-to-end testing framework. If you can add a test or two that would be great.

Also in the spirit of making [smaller changes](https://softwareengineeringdaily.github.io/Frontend/pullrequests/) I would split this into possible two PRs.

**Comment by dasimandl** [comment]
Related to #571
