### ISSUE TITLE
Bug with dropdown (not closing correctly)

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#215]
Seems the menu doesn't always auto close (if nothing is selected and you move your mouse away). 

Main issue: didn't work in the chrome mobile mode (in dev tools).

**Comment by dfcook** [comment]
It's tricky as the mouse leave event has to be on the list rather than the link or it closes immediately. This means that if you don't move the mouse straight down to the list it won't close.

Bootstrap explicitly changed drop downs to trigger on the click event rather than hover in bootstrap 3 I think. Shall I change this to work the same way?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jasonify** [comment]
I think on-click instead of on hover would be fine and cover it for mobile too :)
