### ISSUE TITLE
Wordpress images are loaded over http instead of https

### ISSUE THREAD

**Issue by andrewmarklloyd** [SoftwareEngineeringDaily/sedaily-front-end#228]
When loading the site over `https`, all pages have the "Mixed content warning" in the console. This is because images are loaded from `http://softwareengineeringdaily.com/wp-content/uploads/*` instead of over `https`. I believe this is a quick fix by using the correct protocol. Screenshot attached:

![screen shot 2018-01-25 at 1 17 01 pm](https://user-images.githubusercontent.com/7810418/35412907-a369cca4-01d2-11e8-927d-5fa6484ce836.png)

**Comment by andrewmarklloyd** [comment]
@jasonify same as #227 I think this could be a "good first issue"

**Comment by andrewmarklloyd** [comment]
Not sure if @crablar is referring to this scenario in #209?

**Comment by jasonify** [comment]
I think they might be related and we have probably both problems. Gotta bring this up to a higher priority on my list I think.

**Comment by andrewmarklloyd** [comment]
The image urls come from the API, so I believe this actually needs to be changed in the [API](https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api)

**Comment by andrewmarklloyd** [comment]
I thought changing the [endpoint](https://github.com/SoftwareEngineeringDaily/sedaily-miner/blob/master/index.js#L29) from http vs https would get `featuredImage` urls with https. But when they're [logged](https://github.com/SoftwareEngineeringDaily/sedaily-miner/blob/master/getImg.js#L22) the urls are still http. We could just do a string replace `http` to `https`, seems hacky though.

**Comment by crablar** [comment]
I think we have images around the site that are hosted on places that we don't know if they have HTTPS.

I believe the fix is to save all images to an S3 bucket then serve them over HTTPS. That will be an annoying script to write--but I changed it to "Good First Issue" since it's prob not too tough.

Additional upside to this is saving the images to our own S3 bucket gives predictable SLA instead of relying on janky websites from all around.

**Comment by andrewmarklloyd** [comment]
Sounds good. We can consolidate with #209
