### ISSUE TITLE
"Top" Episodes Not Calculating Correctly

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#317]
This episode has 7 upvotes: https://www.softwaredaily.com/post/5a968be840178500043e947a/Bitcoin-Transactions-with-Daniel-Van-Flymen

If you go to "Top" it does not appear

I saw a few other examples

**Comment by joshmorel** [comment]
It looks like this is because the `loadMore` function in `BaseListView.vue` gets the next 10 by relative date instead of score. This could be resolved in two ways:

1) Just on the front-end - would need to extend the limit in the GET posts request by 10 more. You'd be re-fetching existing data, so not ideal, but maybe acceptable.
2) On front-end and back-end. On the back-end, could either add something specific for this use case (score <=) or build more flexible pagination.
