### ISSUE TITLE
Title on website is missing?

### ISSUE THREAD

**Issue by jasonify** [SoftwareEngineeringDaily/sedaily-front-end#410]
<title> tag doesn't seem to be getting honored?

**Comment by joshmorel** [comment]
My bad... maybe. It seems that because `title` is not defined in `metaInfo` (from `vue-meta`) `<title>` in `index.html` is removed. 

I do find this to be unexpected behaviour as `meta` and `link` tags in `index.html` are not being overwritten. I figure it has to do with `<title>` being a single-only tag while the others can occur multiple times. Even so, it does't seem very consistent so I may open an GitHub issue.
