### ISSUE TITLE
Text width on post should be more narrow (see Medium)

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#628]

**Comment by sterlingrules** [comment]
Do you mean the dedicated post page or the post preview?

Currently, at its largest viewport width, SED's dedicated post text is 652px while Medium is actually 680px. Medium's may seem more narrow because the font size is much larger (21px vs SED's 16px). Do you want to increase the dedicated post text size to match Medium's?
