### ISSUE TITLE
Changes to registration flow

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#694]
- [x] don't require confirming email
- [x] don't require confirming password
- [x] remove the Register for newsletter box component
- [x] change "Name" field to "First Name"
- [x] remove "Bio" and "Website" (but leave these on the Edit Profile page)

**Comment by sterlingrules** [comment]
@crablar I'm trying to add the create account with LinkedIn feature but they require a lot of approvals. Would you mind filling out this form when you can? https://crmnamvoc1runtime.crm.dynamics.com/e13fd46a-3bd4-4f5f-a38b-cffb0f8d6f7d/mdp-app-form-survey/fNE8cXOaEeqoEQANOowCjg2

I will also need you to approve the `sedaily` LinkedIn app I've created in order to allow account creation. https://www.linkedin.com/help/linkedin/answer/102672

**Comment by crablar** [comment]
@sterlingrules filled out the form.

How do I approve the app?

**Comment by sterlingrules** [comment]
I just added you to the LinkedIn app and made you an admin. I'm not sure exactly the next steps, but I believe we'll have to wait for them to approve it and we'll get a notification.

**Comment by crablar** [comment]
@sterlingrules Moving this to @marcosschlup . Let us know when you hear back from LinkedIn.
