### ISSUE TITLE
Published topic not displaying

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#707]
https://www.softwaredaily.com/posts/apache-spark

**Comment by marcosschlup** [comment]
<img width="721" alt="Captura de Tela 2020-03-30 às 10 44 52" src="https://user-images.githubusercontent.com/8609590/77919413-8700bf00-7273-11ea-8a1a-91358b49e8e3.png">

The topic was unpublished, but really, due to the events that we can see in the image, we have a publish status but none of it is unpublish. I will investigate what may have happened. Maybe some error in saving some information

**Comment by marcosschlup** [comment]
Ok, just found the problem. If you edit and save the topic after publish, it returns the status to unpublish. I thing this is confusing, will remove this
