### ISSUE TITLE
Topic Q&A

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#750]
The goal of this feature is to repurpose questions from the SE Daily episodes for a curated Q&A. 

Design: https://www.figma.com/file/MLGq5xD6sAIk8ZCfbnoAKl/Adding-Q-and-A-to-Topic-Pages

Notice the way to add questions in the admin dashboard. The reason is that I have hundreds of outlines like [this](https://docs.google.com/document/d/1EFnAOWxvMTSfS9XOc4-rQnWTsyCkPw4fvBvdAMIMvWA/edit?usp=sharing). I want to be able to select questions from these outlines and quickly paste them into the admin panel to create new questions for the topic Q&A section.

**Comment by crablar** [comment]
This is a big issue so I'd like you guys to work on it together after Marcos finishes what is in progress.

**Comment by sterlingrules** [comment]
@crablar Questions
- Do we need dedicated question edit routes? Do you foresee needing users to directly link into editing a question? In order to simplify, would you be open to offering an **edit** button if the question is owned by the logged in user and then editing in a modal?
- Adding/Editing an answer would work similarly. We could probably even use the same modal for each of these features.

Assuming we simplify the front-end routes, I think this feature would look like the following:

---
## Client Specs
Topic Public:
ie. /topic/kubernetes
I know a general topic page has already been created from the Topic Admin project, so both @marcosschlup and I could continue working on this.

Topic Admin:
ie. /topic
Since @marcosschlup has already been working through this, I figure you could continue to own this, and I can help you if you need me for anything.

Question pages primarily for Social Sharing:
ie. /topic/kubernetes/we-already-had-mesos-kef38jEjkl84
I'd like to take on the question and answering features for the topics.

Answer pages primarily for Social Sharing:
ie. /topic/kubernetes/we-already-had-mesos-kef38jEjkl84#1234
Answer pages should be the question routes with a hash to take users to the properly linked answer.

## API Specs:
- [x] `get /topics`
- [x] `post /topics // creating new topics`
- [x] `get /topics/:topicId`
- [x] `put /topics/:topicId`
- [ ] `get /topics/:topicId/questions // include answers`
- [ ] `post /topics/:topicId/questions`
- [ ] `get /questions/:questioned // include answers`
- [ ] `put /questions/:questionId`
- [ ] `delete /questions/:questionId`
- [ ] `post /questions/:questionId/answers`
- [ ] `put /answers/:answerId`
- [ ] `delete /answers/:answerId`

**Comment by crablar** [comment]
@sterlingrules 

> Do we need dedicated question edit routes? Do you foresee needing users to directly link into editing a question? In order to simplify, would you be open to offering an edit button if the question is owned by the logged in user and then editing in a modal?

Since admin is the only one editing topics right now, we don't need an edit button. That said, admin should be able to edit the questions from the admin panel.

> Can questions only be added by the Topic maintainer? Or can any user ask a question?
Users can't ask questions. The idea is that these are questions I have already prepared.

**Comment by crablar** [comment]
Current outstanding issues from looking at [this topic page](https://sedaily-frontend-staging.herokuapp.com/topic/kubernetes):
- on topic page, change the wording to "...If you want to write about <topic name>, click here." Then there should be a big inviting button to the right of it to click. "Learn more" should be right beneath that, but remove the "Kubernetes" link below
- Below "Learn More" include the questions that have been created

**Comment by crablar** [comment]
From the Vue topic, it looks like [Q&A doesn't work quite yet](https://sedaily-frontend-staging.herokuapp.com/topic/vue).

**Comment by crablar** [comment]
@sterlingrules 

- a user shouldn't be able to add multiple answers
- the default tweet should just have <user>'s answer to <question>.
- the big black text of the question should link to the /topic/<topic>/question/83824
- on the question page, remove the topic text from the top of the page, and just put the small topic link tag at the top

Please test the Q&A feature a bit more yourself and see if you find anything.

**Comment by crablar** [comment]
@sterlingrules looks good to ship! Nice work.
