### ISSUE TITLE
Android main page not loading

### ISSUE THREAD

**Issue by crablar** [SoftwareEngineeringDaily/sedaily-front-end#841]

**Comment by sterlingrules** [comment]
I've taken a look through the server queries and updated a few to make sure the Bearer token is properly formatted — since I know that was an issue in the past — but I'm not able to see what's happening app-side. I also don't see any errors in the server logs related to the Android app. The only other thing I can think of might be some malformed data being returned that the Android app isn't handling well.

**Comment by MostafaGazar** [comment]
Haha, I was just testing it and it was working fine, thanks for finding the cause.

**Comment by crablar** [comment]
Thank you both!
